package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestPerturbSourceNamedBodiesOnly(t *testing.T) {
	source := []byte(`package p

func init() { println("init") }
func Free() int { return func() int { return 1 }() }
func (receiver T) Method() {}
type T int
var Closure = func() { println("closure") }
`)
	got, count, err := perturbSource("ordinary.go", source)
	if err != nil {
		t.Fatal(err)
	}
	if count != 3 {
		t.Fatalf("named body count = %d, want 3", count)
	}
	if occurrences := bytes.Count(got, []byte(`panic("perturbed")`)); occurrences != 3 {
		t.Fatalf("panic count = %d, want 3\n%s", occurrences, got)
	}
	closure := `var Closure = func() { println("closure") }`
	if !strings.Contains(string(got), closure) {
		t.Fatalf("anonymous closure was modified:\n%s", got)
	}
}

func TestExclusions(t *testing.T) {
	cases := []struct {
		name   string
		path   string
		source string
	}{
		{"protobuf", "message.pb.go", "package p\nfunc F() {}\n"},
		{"zz generated", "zz_generated.deepcopy.go", "package p\nfunc F() {}\n"},
		{"build ignore", "tool.go", "//go:build ignore\n\npackage main\nfunc main() {}\n"},
		{"legacy build ignore", "tool.go", "// +build ignore\n\npackage main\nfunc main() {}\n"},
		{"generated header", "gen.go", "// Code generated by test. DO NOT EDIT.\npackage p\nfunc F() {}\n"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, _, err := perturbSource(tc.path, []byte(tc.source))
			if _, ok := err.(*exclusionError); !ok {
				t.Fatalf("error = %T %v, want exclusionError", err, err)
			}
		})
	}
}

func TestWriteExactRoundTrip(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "sample.go")
	original := []byte("package p\r\nfunc F() { println(1) }\r\n")
	if err := os.WriteFile(path, original, 0640); err != nil {
		t.Fatal(err)
	}
	perturbed, _, err := perturbSource(path, original)
	if err != nil {
		t.Fatal(err)
	}
	if err := writeExact(path, perturbed, 0640); err != nil {
		t.Fatal(err)
	}
	if err := writeExact(path, original, 0640); err != nil {
		t.Fatal(err)
	}
	restored, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(restored, original) {
		t.Fatalf("restored bytes differ: %q", restored)
	}
}

func TestPendingInterruptBeforeMutationLeavesOriginal(t *testing.T) {
	directory := t.TempDir()
	target := filepath.Join(directory, "sample.go")
	original := []byte("package p\nfunc F() { println(1) }\n")
	if err := os.WriteFile(target, original, 0644); err != nil {
		t.Fatal(err)
	}

	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	oldArguments := os.Args
	os.Args = []string{executable, "-file", target, "-roundtrip"}
	defer func() { os.Args = oldArguments }()
	interrupts := make(chan os.Signal, 1)
	interrupts <- os.Interrupt

	_, exitCode, runErr := runWithInterrupts(interrupts)
	if runErr == nil || !strings.Contains(runErr.Error(), "interrupted before perturbation") {
		t.Fatalf("error = %v, want pre-perturbation interrupt", runErr)
	}
	if exitCode != 130 {
		t.Fatalf("exit code = %d, want 130", exitCode)
	}
	actual, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(actual, original) {
		t.Fatalf("pending interrupt changed target: %q", actual)
	}
}

func TestInterruptDuringChildRestoresOriginal(t *testing.T) {
	directory := t.TempDir()
	target := filepath.Join(directory, "sample.go")
	marker := filepath.Join(directory, "child-started")
	original := []byte("package p\nfunc F() { println(1) }\n")
	if err := os.WriteFile(target, original, 0644); err != nil {
		t.Fatal(err)
	}

	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	oldArguments := os.Args
	os.Args = []string{executable, "-file", target, "--", executable, "-test.run=^TestPerturbInterruptChild$"}
	defer func() { os.Args = oldArguments }()
	oldMarker, hadMarker := os.LookupEnv("GO_PERTURB_INTERRUPT_MARKER")
	if err := os.Setenv("GO_PERTURB_INTERRUPT_MARKER", marker); err != nil {
		t.Fatal(err)
	}
	defer func() {
		if hadMarker {
			_ = os.Setenv("GO_PERTURB_INTERRUPT_MARKER", oldMarker)
		} else {
			_ = os.Unsetenv("GO_PERTURB_INTERRUPT_MARKER")
		}
	}()

	interrupts := make(chan os.Signal, 1)
	markerObserved := make(chan bool, 1)
	go func() {
		deadline := time.Now().Add(10 * time.Second)
		for time.Now().Before(deadline) {
			if _, statErr := os.Stat(marker); statErr == nil {
				markerObserved <- true
				interrupts <- os.Interrupt
				return
			}
			time.Sleep(10 * time.Millisecond)
		}
		markerObserved <- false
		interrupts <- os.Interrupt
	}()

	result, exitCode, runErr := runWithInterrupts(interrupts)
	if runErr != nil {
		t.Fatal(runErr)
	}
	if !<-markerObserved {
		t.Fatal("child did not reach the interrupt marker")
	}
	if exitCode != 130 {
		t.Fatalf("exit code = %d, want 130", exitCode)
	}
	if result.CommandExitCode == nil || *result.CommandExitCode != 130 {
		t.Fatalf("reported command exit = %v, want 130", result.CommandExitCode)
	}
	restored, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(restored, original) || !result.RestoredExact {
		t.Fatalf("interrupt restore failed: report=%+v bytes=%q", result, restored)
	}
}

func TestPerturbInterruptChild(t *testing.T) {
	marker := os.Getenv("GO_PERTURB_INTERRUPT_MARKER")
	if marker == "" {
		return
	}
	if err := os.WriteFile(marker, []byte("started"), 0644); err != nil {
		t.Fatal(err)
	}
	time.Sleep(30 * time.Second)
}
