"""Mine raw conflicts from real two-parent merges without a working tree.

The canonical operation is ``git merge-tree --write-tree`` against a task-owned
bare mirror.  The command may add trees and blobs to that mirror's object store;
it never updates a ref or touches a working tree.  Canonical JSON is intentionally
free of wall-clock run metadata so an identical frozen repository produces
byte-identical output.
"""

from __future__ import annotations

import argparse
import collections
import contextlib
import dataclasses
import difflib
import hashlib
import json
import os
import platform
import re
import stat
import subprocess
import sys
import threading
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Iterator, Sequence


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = Path(__file__).with_name("repositories.json")
DEFAULT_MIRROR_ROOT = PROJECT_ROOT / "corpus" / "_conflict_mirrors"
DEFAULT_OUTPUT_ROOT = PROJECT_ROOT / "corpus" / "conflicts"

SCHEMA_VERSION = 1
MINER_PROTOCOL_REVISION = "historical-merge-conflict-miner-v5-git-byte-semantics"
CLASSIFICATION_REVISION = "conflict-file-classification-v4-literal-git-path-segments"
TEST_PATH_REVISION = "conflict-test-path-v3-literal-git-path-segments"
OVERLAP_REVISION = "conflict-byte-overlap-v4-pinned-bounded-linear"
CONFLICT_RANGE_REVISION = "merge-tree-marker-ranges-v2-lf-only"
SEQUENCE_MATCHER_PRODUCT_LIMIT = 100_000_000
SEQUENCE_MATCHER_TOTAL_BYTES_LIMIT = 250_000
MINER_SOURCE_SHA256 = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()

SCRUBBED_GIT_ENVIRONMENT_KEYS: tuple[str, ...] = ()
SCRUBBED_GIT_ENVIRONMENT_PREFIXES = ("GIT_",)
DETERMINISTIC_GIT_ENVIRONMENT_OVERRIDES = {
    "GIT_ATTR_NOSYSTEM": "1",
    "GIT_CONFIG_GLOBAL": os.devnull,
    "GIT_CONFIG_NOSYSTEM": "1",
    "GIT_LITERAL_PATHSPECS": "1",
    "GIT_NO_LAZY_FETCH": "1",
    "GIT_NO_REPLACE_OBJECTS": "1",
    "GIT_OPTIONAL_LOCKS": "0",
    "GIT_TERMINAL_PROMPT": "0",
    "LANG": "C",
    "LC_ALL": "C",
    "TZ": "UTC",
}

LOCKFILE_BASENAMES = frozenset(
    {
        "cargo.lock",
        "composer.lock",
        "flake.lock",
        "gemfile.lock",
        "go.sum",
        "gradle.lockfile",
        "manifest.toml",
        "mix.lock",
        "npm-shrinkwrap.json",
        "package-lock.json",
        "package.resolved",
        "packages.lock.json",
        "pdm.lock",
        "pipfile.lock",
        "pnpm-lock.yaml",
        "podfile.lock",
        "poetry.lock",
        "pubspec.lock",
        "renv.lock",
        "uv.lock",
        "yarn.lock",
    }
)
VENDORED_SEGMENTS = frozenset(
    {
        "deps",
        "external",
        "externals",
        "node_modules",
        "third-party",
        "third_party",
        "_vendor",
        "vendor",
        "vendored",
    }
)
GENERATED_SEGMENTS = frozenset(
    {"autogenerated", "generated", "gen", "_gen", "dist", "build", "_build"}
)
GENERATED_SUFFIXES = (
    ".generated.c",
    ".generated.cc",
    ".generated.cpp",
    ".generated.cs",
    ".generated.go",
    ".generated.h",
    ".generated.java",
    ".generated.js",
    ".generated.json",
    ".generated.py",
    ".generated.rs",
    ".generated.ts",
    ".min.css",
    ".min.js",
    ".pb.cc",
    ".pb.go",
    ".pb.h",
    ".pb.java",
    ".pb.rs",
    ".pb.ts",
    ".pb2.py",
)
TEST_SEGMENTS = frozenset(
    {"__tests__", "spec", "specs", "test", "testdata", "testing", "tests"}
)

STAGE_RE = re.compile(rb"^([0-7]{6}) ([0-9a-f]+) ([123])\t([\s\S]*)$")
SLUG_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_.-]*\Z")
HUNK_RE = re.compile(
    rb"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(?: .*)?(?:\r?\n)?$"
)
COMMITTER_RE = re.compile(rb"^committer .* (\d+) [+-]\d{4}$", re.MULTILINE)


CLASSIFICATION_RULE = " ".join(
    (
        "Mutually exclusive priority:",
        "(1) lockfile when the lowercase basename is one of ["
        + ",".join(sorted(LOCKFILE_BASENAMES))
        + "] or ends with .lock;",
        "(2) vendored when any non-filename lowercase Git '/' path segment is one of ["
        + ",".join(sorted(VENDORED_SEGMENTS))
        + "];",
        "(3) generated when any non-filename lowercase Git '/' path segment is one of ["
        + ",".join(sorted(GENERATED_SEGMENTS))
        + "], the lowercase basename ends with one of ["
        + ",".join(GENERATED_SUFFIXES)
        + "] or .map, or a case-insensitive first-8192-byte header contains "
        "@generated, contains 'automatically generated', or contains both "
        "'generated' and 'do not edit'; each available historical stage blob is "
        "checked in stage order and the first header match wins;",
        "(4) handwritten is the operational default. Historical stage blobs, never "
        "a checkout, supply content; a backslash is a literal Git filename byte, not a separator.",
    )
)
TEST_PATH_RULE = (
    "Path-only rule over literal Git '/' segments (backslash is not a separator): "
    "a test/tests/testing/testdata/__tests__/spec/specs segment, "
    "or conftest.py, test_*.py, *_test.py, *_test.go, *_test.rs, *.test.*, *.spec.*, "
    "Java *Test.java/*Tests.java, or conventional C/C++ test_* and *_test names."
)
OVERLAP_RULE = (
    "For each conflict path with stages 1/2/3, Git zero-context, no-indent-heuristic "
    "Myers hunks with zero inter-hunk context, literal a/b prefixes, no relative paths, "
    "and nonignored submodules isolate "
    "changed slices and Python SequenceMatcher(autojunk=False) refines them to raw "
    "byte intervals in the stage-1 blob when every old-slice-by-new-slice byte product "
    f"is at most {SEQUENCE_MATCHER_PRODUCT_LIMIT} and each old+new slice total is at "
    f"most {SEQUENCE_MATCHER_TOTAL_BYTES_LIMIT} bytes; larger paths are retained as "
    "unclassifiable_refinement_limit rather than entering quadratic work. "
    "Replacements/deletions consume zero-based "
    "half-open intervals; insertions are anchors. Strict contact means positive "
    "interval intersection, equal insertion anchors, or an insertion strictly "
    "inside an interval. Contact is computed by linear sweeps/set intersections over "
    "sorted merged intervals and anchors, not Cartesian products. Endpoint-only contact "
    "is boundary_only when every path "
    "is classifiable, or boundary_with_unclassifiable when another path is unknown. "
    "Structural, binary, or missing-stage cases remain unclassifiable."
)
STORAGE_POLICY = (
    "task-owned bare partial mirror; source corpus clones may be used only as "
    "read-only clone-preparation references and are never mined or mutated; "
    "merge-tree may write only unreachable result objects to the task mirror; "
    "no working tree is used"
)
MERGE_TREE_INTERPRETATION = (
    "standalone exit 0=clean; standalone exit 1=conflicted; any other exit or any "
    "nonempty stderr=operational failure; stdout is NUL-delimited result tree, "
    "unmerged stages, separator, and message records; conflict paths are the union "
    "of stage paths and stable CONFLICT message paths"
)


class MiningError(RuntimeError):
    """A deterministic mining invariant failed."""


class MergeTreeOperationalError(MiningError):
    """The exact merge-tree invocation returned neither clean nor conflict."""

    def __init__(self, result: Any):
        self.returncode = int(result.returncode)
        self.stdout = bytes(result.stdout)
        self.stderr = bytes(result.stderr)
        super().__init__(
            f"merge-tree returned operational status {self.returncode}: "
            f"{decode_git_text(self.stderr).strip()}"
        )


class RepositoryLock:
    """An OS-backed single-writer lock released even if a process is killed."""

    def __init__(self, output_root: Path, slug: str):
        self.path = output_root / "_locks" / f"{slug}.lock"
        self.handle: Any = None

    def __enter__(self) -> "RepositoryLock":
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.handle = self.path.open("a+b")
        self.handle.seek(0, os.SEEK_END)
        if self.handle.tell() == 0:
            self.handle.write(b"\0")
            self.handle.flush()
        self.handle.seek(0)
        try:
            if os.name == "nt":
                import msvcrt

                msvcrt.locking(self.handle.fileno(), msvcrt.LK_NBLCK, 1)
            else:
                import fcntl

                fcntl.flock(self.handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError as error:
            self.handle.close()
            self.handle = None
            raise MiningError(
                f"{self.path.stem}: another miner holds the repository output lock"
            ) from error
        return self

    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None:
        if self.handle is None:
            return
        with contextlib.suppress(OSError):
            self.handle.seek(0)
            if os.name == "nt":
                import msvcrt

                msvcrt.locking(self.handle.fileno(), msvcrt.LK_UNLCK, 1)
            else:
                import fcntl

                fcntl.flock(self.handle.fileno(), fcntl.LOCK_UN)
        self.handle.close()
        self.handle = None
        with contextlib.suppress(OSError):
            self.path.unlink()


def canonical_json(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def decode_git_text(value: bytes) -> str:
    return value.decode("utf-8", errors="replace")


def decode_git_path(value: bytes) -> str:
    # ensure_ascii=True serializes surrogate escapes safely and reversibly.
    return value.decode("utf-8", errors="surrogateescape")


def encode_git_path(value: str) -> bytes:
    return value.encode("utf-8", errors="surrogateescape")


def deterministic_git_environment() -> dict[str, str]:
    environment = dict(os.environ)
    for key in list(environment):
        if key in SCRUBBED_GIT_ENVIRONMENT_KEYS or key.startswith(
            SCRUBBED_GIT_ENVIRONMENT_PREFIXES
        ):
            environment.pop(key, None)
    environment.update(DETERMINISTIC_GIT_ENVIRONMENT_OVERRIDES)
    return environment


GIT_CONFIG_ARGS = (
    "-c",
    f"core.attributesFile={os.devnull}",
    "-c",
    "advice.submoduleMergeConflict=false",
    "-c",
    "core.quotePath=true",
    "-c",
    "merge.conflictStyle=merge",
    "-c",
    "merge.renormalize=false",
    "-c",
    "merge.renames=true",
    "-c",
    "merge.directoryRenames=conflict",
    "-c",
    "merge.renameLimit=7000",
    "-c",
    "diff.renames=false",
    "-c",
    "diff.algorithm=myers",
)
MERGE_TREE_INVOCATION = (
    "git",
    *GIT_CONFIG_ARGS,
    "-C",
    "<task-owned-bare-mirror>",
    "merge-tree",
    "--write-tree",
    "-z",
    "--messages",
    "-Xfind-renames=50%",
    "P1",
    "P2",
)


@dataclasses.dataclass(frozen=True)
class GitResult:
    args: tuple[str, ...]
    returncode: int
    stdout: bytes
    stderr: bytes


class GitRepository:
    def __init__(self, path: Path):
        self.path = path.resolve()
        self.environment = deterministic_git_environment()

    def command(self, arguments: Sequence[str]) -> list[str]:
        return [
            "git",
            *GIT_CONFIG_ARGS,
            "-C",
            str(self.path),
            *arguments,
        ]

    def run(
        self,
        arguments: Sequence[str],
        *,
        check: bool = True,
        input_bytes: bytes | None = None,
    ) -> GitResult:
        completed = subprocess.run(
            self.command(arguments),
            input=input_bytes,
            capture_output=True,
            env=self.environment,
            check=False,
        )
        result = GitResult(
            args=tuple(arguments),
            returncode=completed.returncode,
            stdout=completed.stdout,
            stderr=completed.stderr,
        )
        if check and result.returncode != 0:
            stderr = decode_git_text(result.stderr).strip()
            raise MiningError(
                f"git {' '.join(arguments)} failed with {result.returncode}: {stderr}"
            )
        return result

    def text(self, arguments: Sequence[str]) -> str:
        return decode_git_text(self.run(arguments).stdout).strip()


def is_reparse_point(path: Path) -> bool:
    attributes = getattr(path.lstat(), "st_file_attributes", 0)
    return bool(attributes & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0))


def validate_task_mirror(
    mirror_root: Path,
    slug: str,
    repository_spec: dict[str, Any],
) -> tuple[Path, GitRepository, dict[str, Any]]:
    if not SLUG_RE.fullmatch(slug):
        raise MiningError(f"unsafe repository slug {slug!r}")
    if not mirror_root.is_dir():
        raise MiningError(f"mirror root is absent or not a directory: {mirror_root}")
    if mirror_root.is_symlink() or is_reparse_point(mirror_root):
        raise MiningError(
            f"mirror root must not be a symlink or reparse point: {mirror_root}"
        )
    root = mirror_root.resolve(strict=True)
    candidate = root / slug
    if not candidate.is_dir():
        raise MiningError(f"{slug}: missing task-owned mirror {candidate}")
    if candidate.is_symlink() or is_reparse_point(candidate):
        raise MiningError(f"{slug}: task mirror must not be a symlink or reparse point")
    resolved = candidate.resolve(strict=True)
    if resolved.parent != root:
        raise MiningError(f"{slug}: task mirror escapes the declared mirror root")
    alternates = resolved / "objects" / "info" / "alternates"
    if alternates.exists() and alternates.read_bytes().strip():
        raise MiningError(f"{slug}: task mirror has nonempty object alternates")

    repository = GitRepository(resolved)
    if repository.text(["rev-parse", "--is-bare-repository"]) != "true":
        raise MiningError(f"{slug}: mirror is not bare")
    if repository.text(["rev-parse", "--is-shallow-repository"]) != "false":
        raise MiningError(f"{slug}: shallow history would truncate the merge population")
    origin = repository.text(["config", "--get", "remote.origin.url"])
    expected_origin = str(repository_spec.get("url", ""))
    if not expected_origin or origin != expected_origin:
        raise MiningError(
            f"{slug}: mirror origin {origin!r} != manifest origin {expected_origin!r}"
        )
    promisor = repository.text(["config", "--get", "remote.origin.promisor"])
    partial_filter = repository.text(
        ["config", "--get", "remote.origin.partialclonefilter"]
    )
    if promisor != "true" or partial_filter != "blob:none":
        raise MiningError(
            f"{slug}: mirror is not the required promisor blob:none partial mirror"
        )
    return resolved, repository, {
        "alternates": False,
        "bare": True,
        "direct_child": True,
        "origin": origin,
        "partial_clone_filter": partial_filter,
        "promisor": True,
        "reparse_point": False,
        "shallow": False,
    }


def read_nul_field(stream: Any) -> bytes:
    field = bytearray()
    while True:
        chunk = stream.read(1)
        if not chunk:
            raise MiningError("NUL-framed cat-file stream ended before a terminator")
        if chunk == b"\0":
            return bytes(field)
        field.extend(chunk)


class BatchCatFile:
    """Long-lived cat-file process for commit/blob reads."""

    def __init__(self, repository: GitRepository):
        self.repository = repository
        self.process: subprocess.Popen[bytes] | None = None
        self.cache: dict[bytes, tuple[str, str, bytes] | None] = {}

    def __enter__(self) -> "BatchCatFile":
        self.process = subprocess.Popen(
            self.repository.command(["cat-file", "--batch", "-Z"]),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=self.repository.environment,
        )
        return self

    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None:
        if self.process is None:
            return
        if self.process.stdin:
            self.process.stdin.close()
        try:
            self.process.wait(timeout=30)
        except subprocess.TimeoutExpired:
            self.process.kill()
            self.process.wait()
        if exc_type is None and self.process.returncode not in (0, None):
            stderr = b"" if self.process.stderr is None else self.process.stderr.read()
            raise MiningError(
                f"git cat-file --batch failed: {decode_git_text(stderr).strip()}"
            )

    def get_with_oid(
        self, specification: bytes | str
    ) -> tuple[str, str, bytes] | None:
        if isinstance(specification, str):
            key = specification.encode("ascii")
        else:
            key = specification
        if key in self.cache:
            return self.cache[key]
        if b"\0" in key:
            self.cache[key] = None
            return None
        if self.process is None or self.process.stdin is None or self.process.stdout is None:
            raise MiningError("cat-file batch process is not running")
        self.process.stdin.write(key + b"\0")
        self.process.stdin.flush()
        header = read_nul_field(self.process.stdout)
        if header.endswith(b" missing"):
            self.cache[key] = None
            return None
        try:
            oid_raw, object_type, size_raw = header.rsplit(b" ", 2)
            size = int(size_raw)
        except (ValueError, TypeError) as error:
            raise MiningError(f"invalid cat-file header: {header!r}") from error
        payload = self.process.stdout.read(size)
        terminator = self.process.stdout.read(1)
        if len(payload) != size or terminator != b"\0":
            raise MiningError("truncated cat-file batch payload")
        answer = (
            oid_raw.decode("ascii"),
            object_type.decode("ascii"),
            payload,
        )
        self.cache[key] = answer
        return answer

    def get(self, specification: bytes | str) -> tuple[str, bytes] | None:
        answer = self.get_with_oid(specification)
        if answer is None:
            return None
        return answer[1], answer[2]


@dataclasses.dataclass
class Hunk:
    old_start: int
    old_count: int
    new_start: int
    new_count: int


@dataclasses.dataclass
class FileDiff:
    path_raw: bytes
    hunks: list[Hunk] = dataclasses.field(default_factory=list)
    binary: bool = False

    @property
    def path(self) -> str:
        return decode_git_path(self.path_raw)


def _unquote_c_path(token: bytes) -> bytes:
    if not (token.startswith(b'"') and token.endswith(b'"')):
        return token
    source = token[1:-1]
    result = bytearray()
    index = 0
    escapes = {
        ord("a"): 7,
        ord("b"): 8,
        ord("t"): 9,
        ord("n"): 10,
        ord("v"): 11,
        ord("f"): 12,
        ord("r"): 13,
        ord('"'): 34,
        ord("\\"): 92,
    }
    while index < len(source):
        value = source[index]
        if value != 92:
            result.append(value)
            index += 1
            continue
        index += 1
        if index >= len(source):
            result.append(92)
            break
        escaped = source[index]
        if escaped in escapes:
            result.append(escapes[escaped])
            index += 1
            continue
        if 48 <= escaped <= 55:
            end = index
            while end < len(source) and end < index + 3 and 48 <= source[end] <= 55:
                end += 1
            result.append(int(source[index:end], 8))
            index = end
            continue
        result.append(escaped)
        index += 1
    return bytes(result)


def _parse_quoted_token(payload: bytes, start: int) -> tuple[bytes, int]:
    if payload[start] != 34:
        end = payload.find(b" ", start)
        if end == -1:
            end = len(payload)
        return payload[start:end], end
    index = start + 1
    escaped = False
    while index < len(payload):
        value = payload[index]
        if value == 34 and not escaped:
            return payload[start : index + 1], index + 1
        if value == 92 and not escaped:
            escaped = True
        else:
            escaped = False
        index += 1
    raise MiningError(f"unterminated quoted diff path: {payload!r}")


def parse_diff_git_path(line: bytes) -> bytes:
    payload = line[len(b"diff --git ") :].rstrip(b"\r\n")
    if payload.startswith(b'"'):
        _old_token, end = _parse_quoted_token(payload, 0)
        while end < len(payload) and payload[end] == 32:
            end += 1
        new_token, _ = _parse_quoted_token(payload, end)
        decoded = _unquote_c_path(new_token)
        return decoded[2:] if decoded.startswith(b"b/") else decoded

    # With rename detection disabled old and new paths are identical.  This
    # equality makes even unquoted spaces unambiguous.
    marker = b" b/"
    search = 0
    while True:
        position = payload.find(marker, search)
        if position < 0:
            break
        old_value = payload[:position]
        new_value = payload[position + 1 :]
        if old_value.startswith(b"a/") and new_value.startswith(b"b/"):
            if old_value[2:] == new_value[2:]:
                return new_value[2:]
        search = position + 1
    position = payload.find(marker)
    if position >= 0:
        return payload[position + len(marker) :]
    raise MiningError(f"cannot parse diff path header: {line!r}")


def parse_patch(patch: bytes) -> list[FileDiff]:
    files: list[FileDiff] = []
    current: FileDiff | None = None
    for line in split_lf_lines(patch):
        if line.startswith(b"diff --git "):
            current = FileDiff(parse_diff_git_path(line))
            files.append(current)
            continue
        if current is None:
            continue
        match = HUNK_RE.match(line)
        if match:
            old_start = int(match.group(1))
            old_count = int(match.group(2) or b"1")
            new_start = int(match.group(3))
            new_count = int(match.group(4) or b"1")
            current.hunks.append(Hunk(old_start, old_count, new_start, new_count))
        elif line.startswith(b"Binary files ") or line.startswith(b"GIT binary patch"):
            current.binary = True
    return files


def is_test_path(path: str) -> bool:
    pure = PurePosixPath(path)
    parts = [part.lower() for part in pure.parts]
    if any(part in TEST_SEGMENTS for part in parts[:-1]):
        return True
    name = parts[-1] if parts else ""
    stem = PurePosixPath(name).stem.lower()
    suffix = PurePosixPath(name).suffix.lower()
    if name == "conftest.py":
        return True
    if name.startswith("test_") and suffix in {".py", ".c", ".cc", ".cpp", ".cxx"}:
        return True
    if stem.endswith("_test") and suffix in {
        ".py",
        ".go",
        ".rs",
        ".c",
        ".cc",
        ".cpp",
        ".cxx",
    }:
        return True
    if ".test." in name or ".spec." in name:
        return True
    if suffix == ".java" and (stem.endswith("test") or stem.endswith("tests")):
        return True
    return False


def classify_path(path: str, historical_blobs: Sequence[tuple[str, bytes]]) -> dict[str, Any]:
    pure = PurePosixPath(path)
    parts = [part.lower() for part in pure.parts]
    name = parts[-1] if parts else ""
    if name in LOCKFILE_BASENAMES or name.endswith(".lock"):
        return {"kind": "lockfile", "rule": "lockfile-basename-or-suffix"}
    matched_vendor = next((part for part in parts[:-1] if part in VENDORED_SEGMENTS), None)
    if matched_vendor is not None:
        return {"kind": "vendored", "rule": f"vendored-segment:{matched_vendor}"}
    matched_generated = next(
        (part for part in parts[:-1] if part in GENERATED_SEGMENTS), None
    )
    if matched_generated is not None:
        return {"kind": "generated", "rule": f"generated-segment:{matched_generated}"}
    if any(name.endswith(suffix) for suffix in GENERATED_SUFFIXES) or name.endswith(".map"):
        return {"kind": "generated", "rule": "generated-suffix"}
    for oid, blob in historical_blobs:
        header = blob[:8192].lower()
        if b"@generated" in header or b"automatically generated" in header or (
            b"generated" in header and b"do not edit" in header
        ):
            return {
                "kind": "generated",
                "rule": "generated-header-first-8192-bytes",
                "evidence_blob": oid,
            }
    return {"kind": "handwritten", "rule": "operational-default"}


def diff_stats(files: Sequence[FileDiff]) -> dict[str, Any]:
    added = sum(hunk.new_count for file in files for hunk in file.hunks)
    deleted = sum(hunk.old_count for file in files for hunk in file.hunks)
    binary_paths = sorted(file.path for file in files if file.binary)
    test_paths = sorted(file.path for file in files if is_test_path(file.path))
    return {
        "binary_files": len(binary_paths),
        "binary_paths": binary_paths,
        "files": len(files),
        "hunks": sum(len(file.hunks) for file in files),
        "lines_added": added,
        "lines_changed": None if binary_paths else added + deleted,
        "lines_deleted": deleted,
        "test_files": test_paths,
        "text_lines_changed": added + deleted,
        "touches_tests": bool(test_paths),
    }


def split_lf_lines(blob: bytes) -> list[bytes]:
    """Split exactly as Git's text diff does: LF terminates a line; other bytes do not."""

    lines: list[bytes] = []
    start = 0
    while start < len(blob):
        newline = blob.find(b"\n", start)
        if newline < 0:
            lines.append(blob[start:])
            break
        lines.append(blob[start : newline + 1])
        start = newline + 1
    return lines


def git_line_body(line: bytes) -> bytes:
    """Remove one LF and its immediately preceding CR, preserving every other CR."""

    if not line.endswith(b"\n"):
        return line
    body = line[:-1]
    return body[:-1] if body.endswith(b"\r") else body


def line_offsets(blob: bytes) -> list[int]:
    offsets = [0]
    running = 0
    for line in split_lf_lines(blob):
        running += len(line)
        offsets.append(running)
    return offsets


def hunk_slice(offsets: Sequence[int], start: int, count: int, size: int) -> tuple[int, int]:
    if count == 0:
        # Git's zero-length old range is anchored after `start` existing lines.
        anchor_index = min(max(start, 0), len(offsets) - 1)
        anchor = offsets[anchor_index]
        return anchor, anchor
    first = min(max(start - 1, 0), len(offsets) - 1)
    last = min(first + count, len(offsets) - 1)
    return min(offsets[first], size), min(offsets[last], size)


def merge_intervals(ranges: Iterable[tuple[int, int]]) -> list[tuple[int, int]]:
    ordered = sorted((start, end) for start, end in ranges if start < end)
    merged: list[list[int]] = []
    for start, end in ordered:
        if not merged or start > merged[-1][1]:
            merged.append([start, end])
        else:
            merged[-1][1] = max(merged[-1][1], end)
    return [(start, end) for start, end in merged]


def changed_base_ranges(
    base_blob: bytes,
    side_blob: bytes,
    hunks: Sequence[Hunk],
) -> tuple[list[tuple[int, int]], list[int]]:
    base_offsets = line_offsets(base_blob)
    side_offsets = line_offsets(side_blob)
    intervals: list[tuple[int, int]] = []
    anchors: list[int] = []
    for hunk in hunks:
        old_start, old_end = hunk_slice(
            base_offsets, hunk.old_start, hunk.old_count, len(base_blob)
        )
        new_start, new_end = hunk_slice(
            side_offsets, hunk.new_start, hunk.new_count, len(side_blob)
        )
        old_slice = base_blob[old_start:old_end]
        new_slice = side_blob[new_start:new_end]
        matcher = difflib.SequenceMatcher(None, old_slice, new_slice, autojunk=False)
        for tag, i1, i2, _j1, _j2 in matcher.get_opcodes():
            if tag == "equal":
                continue
            if i1 == i2:
                anchors.append(old_start + i1)
            else:
                intervals.append((old_start + i1, old_start + i2))
    return merge_intervals(intervals), sorted(set(anchors))


def hunk_refinement_products(
    base_blob: bytes,
    side_blob: bytes,
    hunks: Sequence[Hunk],
) -> list[int]:
    """Return deterministic per-hunk byte products without refining the bytes."""
    base_offsets = line_offsets(base_blob)
    side_offsets = line_offsets(side_blob)
    products: list[int] = []
    for hunk in hunks:
        old_start, old_end = hunk_slice(
            base_offsets, hunk.old_start, hunk.old_count, len(base_blob)
        )
        new_start, new_end = hunk_slice(
            side_offsets, hunk.new_start, hunk.new_count, len(side_blob)
        )
        products.append((old_end - old_start) * (new_end - new_start))
    return products


def hunk_refinement_total_bytes(
    base_blob: bytes,
    side_blob: bytes,
    hunks: Sequence[Hunk],
) -> list[int]:
    """Return per-hunk old+new slice bytes, including one-sided edits."""

    base_offsets = line_offsets(base_blob)
    side_offsets = line_offsets(side_blob)
    totals: list[int] = []
    for hunk in hunks:
        old_start, old_end = hunk_slice(
            base_offsets, hunk.old_start, hunk.old_count, len(base_blob)
        )
        new_start, new_end = hunk_slice(
            side_offsets, hunk.new_start, hunk.new_count, len(side_blob)
        )
        totals.append((old_end - old_start) + (new_end - new_start))
    return totals


def strict_contact(
    intervals1: Sequence[tuple[int, int]],
    anchors1: Sequence[int],
    intervals2: Sequence[tuple[int, int]],
    anchors2: Sequence[int],
) -> bool:
    if set(anchors1).intersection(anchors2):
        return True

    left = right = 0
    while left < len(intervals1) and right < len(intervals2):
        a, b = intervals1[left]
        c, d = intervals2[right]
        if max(a, c) < min(b, d):
            return True
        if b <= d:
            left += 1
        else:
            right += 1

    def anchor_inside(
        intervals: Sequence[tuple[int, int]], anchors: Sequence[int]
    ) -> bool:
        interval_index = 0
        for anchor in anchors:
            while (
                interval_index < len(intervals)
                and intervals[interval_index][1] <= anchor
            ):
                interval_index += 1
            if interval_index >= len(intervals):
                return False
            start, end = intervals[interval_index]
            if start < anchor < end:
                return True
        return False

    if anchor_inside(intervals1, anchors2) or anchor_inside(intervals2, anchors1):
        return True
    return False


def boundary_contact(
    intervals1: Sequence[tuple[int, int]],
    anchors1: Sequence[int],
    intervals2: Sequence[tuple[int, int]],
    anchors2: Sequence[int],
) -> bool:
    starts1 = {start for start, _end in intervals1}
    ends1 = {end for _start, end in intervals1}
    starts2 = {start for start, _end in intervals2}
    ends2 = {end for _start, end in intervals2}
    endpoints1 = starts1 | ends1
    endpoints2 = starts2 | ends2
    return bool(
        (ends1 & starts2)
        or (ends2 & starts1)
        or (endpoints1 & set(anchors2))
        or (endpoints2 & set(anchors1))
    )


def marker_regions(blob: bytes, oid: str) -> tuple[str, list[dict[str, Any]]]:
    if b"\0" in blob:
        return "unavailable_binary_result", []
    lines = split_lf_lines(blob)
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line))
    regions: list[dict[str, Any]] = []
    index = 0
    while index < len(lines):
        body = git_line_body(lines[index])
        marker_size = 0
        while marker_size < len(body) and body[marker_size] == 60:
            marker_size += 1
        if marker_size < 7 or marker_size == len(body):
            index += 1
            continue
        separator = None
        closing = None
        scan = index + 1
        while scan < len(lines):
            candidate = git_line_body(lines[scan])
            if separator is None and candidate == b"=" * marker_size:
                separator = scan
            elif separator is not None and candidate.startswith(b">" * marker_size):
                if len(candidate) == marker_size or candidate[marker_size : marker_size + 1] in {
                    b" ",
                    b"\t",
                }:
                    closing = scan
                    break
            scan += 1
        if separator is None or closing is None:
            return "unavailable_unbalanced_markers", []
        regions.append(
            {
                "blob_oid": oid,
                "blob_size": len(blob),
                "byte_end": offsets[closing + 1],
                "byte_start": offsets[index],
                "coordinate_space": "merge-tree-result-blob",
                "includes_marker_lines": True,
                "line_end": closing + 1,
                "line_start": index + 1,
                "marker_size": marker_size,
            }
        )
        index = closing + 1
    if not regions:
        return "unavailable_no_text_markers", []
    return "measured_text_markers", regions


def parse_merge_tree_output(output: bytes) -> tuple[str, list[dict[str, Any]], list[dict[str, Any]]]:
    if not output.endswith(b"\0"):
        raise MiningError("merge-tree output lacks its terminal NUL")
    fields = output.split(b"\0")
    if not fields or not re.fullmatch(rb"[0-9a-f]+", fields[0]):
        raise MiningError(f"merge-tree did not start with a tree OID: {output[:200]!r}")
    result_tree = fields[0].decode("ascii")
    stages: list[dict[str, Any]] = []
    seen_stages: set[tuple[str, int]] = set()
    index = 1
    while index < len(fields) and fields[index]:
        match = STAGE_RE.match(fields[index])
        if not match:
            raise MiningError(f"invalid merge-tree stage field: {fields[index]!r}")
        stage_path = decode_git_path(match.group(4))
        stage_number = int(match.group(3))
        stage_key = (stage_path, stage_number)
        if stage_key in seen_stages:
            raise MiningError(f"duplicate merge-tree stage record: {stage_key!r}")
        seen_stages.add(stage_key)
        stages.append(
            {
                "blob": match.group(2).decode("ascii"),
                "mode": match.group(1).decode("ascii"),
                "path": stage_path,
                "stage": stage_number,
            }
        )
        index += 1
    if index < len(fields) and not fields[index]:
        index += 1
    messages: list[dict[str, Any]] = []
    while index < len(fields):
        if not fields[index]:
            index += 1
            continue
        if not re.fullmatch(rb"[0-9]+", fields[index]):
            raise MiningError(f"invalid merge-tree message path count: {fields[index]!r}")
        path_count = int(fields[index])
        index += 1
        if index + path_count + 2 > len(fields):
            raise MiningError("truncated merge-tree message record")
        paths = [decode_git_path(value) for value in fields[index : index + path_count]]
        index += path_count
        short_type = decode_git_text(fields[index])
        human_message = decode_git_text(fields[index + 1])
        index += 2
        if short_type.startswith("CONFLICT") and path_count == 0:
            raise MiningError("CONFLICT message record has no paths")
        messages.append(
            {"message": human_message, "paths": paths, "type": short_type}
        )
    return result_tree, stages, messages


def commit_metadata(cat_file: BatchCatFile, oid: str) -> dict[str, Any]:
    result = cat_file.get(oid)
    if result is None or result[0] != "commit":
        raise MiningError(f"missing commit object {oid}")
    payload = result[1]
    header, separator, message = payload.partition(b"\n\n")
    if not separator:
        message = b""
    match = COMMITTER_RE.search(header)
    if not match:
        raise MiningError(f"commit {oid} lacks a parseable committer timestamp")
    decoded_message = decode_git_text(message)
    subject_bytes = message.split(b"\n", 1)[0]
    if subject_bytes.endswith(b"\r"):
        subject_bytes = subject_bytes[:-1]
    subject = decode_git_text(subject_bytes)
    return {
        "committer_epoch": int(match.group(1)),
        "message": decoded_message,
        "message_sha256": hashlib.sha256(message).hexdigest(),
        "subject": subject,
    }


def find_tree_entry(
    cat_file: BatchCatFile, tree: str, raw_path: bytes
) -> tuple[str, str] | None:
    """Resolve a literal Git path while distinguishing absence from missing objects."""

    segments = raw_path.split(b"/")
    if not raw_path or any(not segment for segment in segments):
        raise MiningError(f"invalid literal Git tree path: {raw_path!r}")
    current_tree = tree
    for position, segment in enumerate(segments):
        result = cat_file.get_with_oid(current_tree)
        if result is None:
            raise MiningError(f"tree object {current_tree} is missing")
        resolved_oid, object_type, payload = result
        if object_type != "tree":
            raise MiningError(f"object {current_tree} has type {object_type!r}, not tree")
        try:
            raw_oid_size = len(bytes.fromhex(resolved_oid))
        except ValueError as error:
            raise MiningError(f"tree object has invalid OID {resolved_oid!r}") from error
        index = 0
        matched: tuple[str, str] | None = None
        while index < len(payload):
            space = payload.find(b" ", index)
            nul = payload.find(b"\0", space + 1) if space >= 0 else -1
            oid_end = nul + 1 + raw_oid_size
            if space < 0 or nul < 0 or oid_end > len(payload):
                raise MiningError(f"tree object {resolved_oid} has malformed entries")
            mode = payload[index:space].decode("ascii", errors="strict")
            name = payload[space + 1 : nul]
            entry_oid = payload[nul + 1 : oid_end].hex()
            index = oid_end
            if name == segment:
                matched = (mode, entry_oid)
                break
        if matched is None:
            return None
        mode, entry_oid = matched
        if position == len(segments) - 1:
            return mode, entry_oid
        if mode not in {"40000", "040000"}:
            return None
        current_tree = entry_oid
    raise AssertionError("literal tree traversal did not terminate")


def tree_blob(
    cat_file: BatchCatFile, tree: str, path: str
) -> tuple[str, bytes] | None:
    entry = find_tree_entry(cat_file, tree, encode_git_path(path))
    if entry is None:
        return None
    mode, oid = entry
    if mode in {"40000", "040000", "160000"}:
        return None
    result = cat_file.get(oid)
    if result is None:
        raise MiningError(f"present result-tree blob {oid} is missing")
    if result[0] != "blob":
        raise MiningError(
            f"present result-tree entry {oid} has type {result[0]!r}, not blob"
        )
    return oid, result[1]


def stage_blob(cat_file: BatchCatFile, entry: dict[str, Any] | None) -> tuple[str, bytes] | None:
    if entry is None or entry["mode"] == "160000":
        return None
    result = cat_file.get(entry["blob"])
    if result is None:
        raise MiningError(f"present stage blob {entry['blob']} is missing")
    if result[0] != "blob":
        raise MiningError(
            f"present non-gitlink stage {entry['blob']} has type {result[0]!r}, not blob"
        )
    return entry["blob"], result[1]


def blob_diff(repository: GitRepository, old_oid: str, new_oid: str) -> list[FileDiff]:
    result = repository.run(
        [
            "diff",
            "--no-ext-diff",
            "--no-textconv",
            "--no-renames",
            "--no-indent-heuristic",
            "--inter-hunk-context=0",
            "--ignore-submodules=none",
            "--src-prefix=a/",
            "--dst-prefix=b/",
            "--no-relative",
            "--diff-algorithm=myers",
            "--unified=0",
            "--no-color",
            old_oid,
            new_oid,
            "--",
        ]
    )
    return parse_patch(result.stdout)


def overlap_for_conflicts(
    repository: GitRepository,
    cat_file: BatchCatFile,
    conflict_paths: Sequence[str],
    stages: Sequence[dict[str, Any]],
) -> dict[str, Any]:
    by_path: dict[str, dict[int, dict[str, Any]]] = {}
    for entry in stages:
        by_path.setdefault(entry["path"], {})[entry["stage"]] = entry
    path_records: list[dict[str, Any]] = []
    strict_paths: list[str] = []
    boundary_paths: list[str] = []
    unclassifiable_paths: list[str] = []
    classifiable_count = 0
    for path in sorted(conflict_paths):
        entries = by_path.get(path, {})
        base = stage_blob(cat_file, entries.get(1))
        side1 = stage_blob(cat_file, entries.get(2))
        side2 = stage_blob(cat_file, entries.get(3))
        record: dict[str, Any] = {"path": path}
        if base is None or side1 is None or side2 is None:
            record["status"] = "unclassifiable_missing_or_nonblob_stage"
            unclassifiable_paths.append(path)
            path_records.append(record)
            continue
        if b"\0" in base[1] or b"\0" in side1[1] or b"\0" in side2[1]:
            record.update(
                {
                    "base_blob": base[0],
                    "status": "unclassifiable_binary",
                }
            )
            unclassifiable_paths.append(path)
            path_records.append(record)
            continue
        diff1 = blob_diff(repository, base[0], side1[0])
        diff2 = blob_diff(repository, base[0], side2[0])
        if any(file.binary for file in diff1 + diff2):
            record.update(
                {
                    "base_blob": base[0],
                    "status": "unclassifiable_binary_by_git",
                }
            )
            unclassifiable_paths.append(path)
            path_records.append(record)
            continue
        hunks1 = [hunk for file in diff1 for hunk in file.hunks]
        hunks2 = [hunk for file in diff2 for hunk in file.hunks]
        products1 = hunk_refinement_products(base[1], side1[1], hunks1)
        products2 = hunk_refinement_products(base[1], side2[1], hunks2)
        totals1 = hunk_refinement_total_bytes(base[1], side1[1], hunks1)
        totals2 = hunk_refinement_total_bytes(base[1], side2[1], hunks2)
        maximum1 = max(products1, default=0)
        maximum2 = max(products2, default=0)
        maximum_total1 = max(totals1, default=0)
        maximum_total2 = max(totals2, default=0)
        if (
            max(maximum1, maximum2) > SEQUENCE_MATCHER_PRODUCT_LIMIT
            or max(maximum_total1, maximum_total2)
            > SEQUENCE_MATCHER_TOTAL_BYTES_LIMIT
        ):
            record.update(
                {
                    "base_blob": base[0],
                    "base_blob_size": len(base[1]),
                    "parent1_max_refinement_product": maximum1,
                    "parent1_max_refinement_total_bytes": maximum_total1,
                    "parent2_max_refinement_product": maximum2,
                    "parent2_max_refinement_total_bytes": maximum_total2,
                    "refinement_product_limit": SEQUENCE_MATCHER_PRODUCT_LIMIT,
                    "refinement_total_bytes_limit": SEQUENCE_MATCHER_TOTAL_BYTES_LIMIT,
                    "status": "unclassifiable_refinement_limit",
                }
            )
            unclassifiable_paths.append(path)
            path_records.append(record)
            continue
        intervals1, anchors1 = changed_base_ranges(base[1], side1[1], hunks1)
        intervals2, anchors2 = changed_base_ranges(base[1], side2[1], hunks2)
        if not (intervals1 or anchors1) or not (intervals2 or anchors2):
            record.update(
                {
                    "base_blob": base[0],
                    "base_blob_size": len(base[1]),
                    "status": "unclassifiable_no_text_byte_change",
                }
            )
            unclassifiable_paths.append(path)
            path_records.append(record)
            continue
        strict = strict_contact(intervals1, anchors1, intervals2, anchors2)
        boundary = False if strict else boundary_contact(
            intervals1, anchors1, intervals2, anchors2
        )
        classifiable_count += 1
        if strict:
            strict_paths.append(path)
        elif boundary:
            boundary_paths.append(path)
        record.update(
            {
                "base_blob": base[0],
                "base_blob_size": len(base[1]),
                "boundary_contact": boundary,
                "parent1": {
                    "anchors": anchors1,
                    "blob": side1[0],
                    "intervals": [[start, end] for start, end in intervals1],
                },
                "parent2": {
                    "anchors": anchors2,
                    "blob": side2[0],
                    "intervals": [[start, end] for start, end in intervals2],
                },
                "status": "classifiable",
                "strict_overlap": strict,
            }
        )
        path_records.append(record)
    if strict_paths:
        classification = "overlap"
    elif boundary_paths and unclassifiable_paths:
        classification = "boundary_with_unclassifiable"
    elif boundary_paths:
        classification = "boundary_only"
    elif classifiable_count and unclassifiable_paths:
        classification = "mixed_unclassifiable"
    elif classifiable_count:
        classification = "same_file_disjoint"
    else:
        classification = "unclassifiable"
    return {
        "boundary_contact_paths": boundary_paths,
        "classifiable_paths": classifiable_count,
        "classification": classification,
        "paths": path_records,
        "rule_revision": OVERLAP_REVISION,
        "strict_overlap_paths": strict_paths,
        "unclassifiable_paths": unclassifiable_paths,
    }


def conflict_details(
    repository: GitRepository,
    cat_file: BatchCatFile,
    result_tree: str,
    conflict_paths: Sequence[str],
    stages: Sequence[dict[str, Any]],
    messages: Sequence[dict[str, Any]],
) -> list[dict[str, Any]]:
    entries_by_path: dict[str, list[dict[str, Any]]] = {}
    for entry in stages:
        entries_by_path.setdefault(entry["path"], []).append(entry)
    types_by_path: dict[str, set[str]] = {}
    for message in messages:
        if message["type"].startswith("CONFLICT"):
            for path in message["paths"]:
                types_by_path.setdefault(path, set()).add(message["type"])
    details: list[dict[str, Any]] = []
    for path in sorted(conflict_paths):
        stage_entries = sorted(
            entries_by_path.get(path, []), key=lambda item: (item["stage"], item["blob"])
        )
        historical_blobs: list[tuple[str, bytes]] = []
        for entry in stage_entries:
            blob = stage_blob(cat_file, entry)
            if blob is not None:
                historical_blobs.append(blob)
        classification = classify_path(path, historical_blobs)
        result = tree_blob(cat_file, result_tree, path)
        if result is None:
            range_status = "unavailable_no_result_blob"
            regions: list[dict[str, Any]] = []
            result_record = None
        else:
            range_status, regions = marker_regions(result[1], result[0])
            result_record = {"oid": result[0], "size": len(result[1])}
        conflicted_bytes = sum(region["byte_end"] - region["byte_start"] for region in regions)
        detail: dict[str, Any] = {
            "classification": classification,
            "conflict_types": sorted(types_by_path.get(path, set())),
            "conflicted_bytes": conflicted_bytes if regions else None,
            "is_test": is_test_path(path),
            "path": path,
            "range_status": range_status,
            "regions": regions,
            "result_blob": result_record,
            "stage_entries": stage_entries,
        }
        if regions and result_record and result_record["size"]:
            detail["conflicted_fraction"] = conflicted_bytes / result_record["size"]
        else:
            detail["conflicted_fraction"] = None
        details.append(detail)
    return details


def repository_diff(repository: GitRepository, base: str, parent: str) -> tuple[list[FileDiff], dict[str, Any]]:
    result = repository.run(
        [
            "diff",
            "--no-ext-diff",
            "--no-textconv",
            "--no-renames",
            "--no-indent-heuristic",
            "--inter-hunk-context=0",
            "--ignore-submodules=none",
            "--src-prefix=a/",
            "--dst-prefix=b/",
            "--no-relative",
            "--diff-algorithm=myers",
            "--unified=0",
            "--no-color",
            base,
            parent,
            "--",
        ]
    )
    files = parse_patch(result.stdout)
    return files, diff_stats(files)


def commit_count(repository: GitRepository, base: str, parent: str) -> int:
    value = repository.text(["rev-list", "--count", f"{base}..{parent}"])
    return int(value)


def primary_merge_base(
    repository: GitRepository, parent1: str, parent2: str
) -> str | None:
    result = repository.run(["merge-base", parent1, parent2], check=False)
    if result.returncode == 1 and not result.stdout.strip():
        return None
    if result.returncode != 0:
        raise MiningError(
            f"merge-base returned operational status {result.returncode}: "
            f"{decode_git_text(result.stderr).strip()}"
        )
    lines = result.stdout.splitlines()
    if len(lines) != 1 or not re.fullmatch(rb"[0-9a-f]+", lines[0]):
        raise MiningError(f"merge-base returned {len(lines)} noncanonical rows")
    return lines[0].decode("ascii")


def merge_tree(
    repository: GitRepository, parent1: str, parent2: str
) -> tuple[bool, str, list[dict[str, Any]], list[dict[str, Any]], str]:
    arguments = [
        "merge-tree",
        "--write-tree",
        "-z",
        "--messages",
        "-Xfind-renames=50%",
        parent1,
        parent2,
    ]
    result = repository.run(arguments, check=False)
    if result.returncode not in (0, 1):
        raise MergeTreeOperationalError(result)
    result_tree, stages, messages = parse_merge_tree_output(result.stdout)
    conflicted = result.returncode == 1
    if result.stderr:
        raise MiningError(
            f"merge-tree status {result.returncode} wrote stderr: "
            f"{decode_git_text(result.stderr).strip()}"
        )
    conflict_message_paths = {
        path
        for message in messages
        if message["type"].startswith("CONFLICT")
        for path in message["paths"]
    }
    stage_paths = {entry["path"] for entry in stages}
    if not conflicted and (stages or conflict_message_paths):
        raise MiningError(
            "merge-tree exit 0 emitted unmerged stages or CONFLICT message paths"
        )
    if conflicted and not (stage_paths or conflict_message_paths):
        raise MiningError("merge-tree exit 1 emitted no conflict paths")
    output_sha256 = hashlib.sha256(result.stdout).hexdigest()
    return conflicted, result_tree, stages, messages, output_sha256


def list_history(repository: GitRepository, head: str) -> tuple[int, list[tuple[str, list[str]]], int]:
    result = repository.run(["rev-list", "--first-parent", "--parents", "--reverse", head])
    rows: list[tuple[str, list[str]]] = []
    total = 0
    octopus = 0
    for raw_line in result.stdout.splitlines():
        fields = raw_line.decode("ascii").split()
        if not fields:
            continue
        total += 1
        parents = fields[1:]
        if len(parents) >= 2:
            if len(parents) == 2:
                rows.append((fields[0], parents))
            else:
                octopus += 1
    return total, rows, octopus


def atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".partial")
    temporary.write_text(canonical_json(value) + "\n", encoding="utf-8", newline="\n")
    os.replace(temporary, path)


def load_resume_rows(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for number, line in enumerate(handle, 1):
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as error:
                raise MiningError(f"invalid resume row {path}:{number}: {error}") from error
    return rows


def open_partial(path: Path, resume: bool) -> tuple[Any, list[dict[str, Any]]]:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = path.with_name(path.name + ".partial")
    existing = load_resume_rows(partial) if resume else []
    mode = "a" if existing else "w"
    return partial.open(mode, encoding="utf-8", newline="\n"), existing


@dataclasses.dataclass(frozen=True)
class MergeEvaluation:
    """One fully enriched merge result, ready for ordered checkpointing."""

    all_row: dict[str, Any]
    conflict_row: dict[str, Any] | None
    multiple_merge_bases: bool
    no_merge_base: bool


@dataclasses.dataclass
class _EvaluationResources:
    cat_file: BatchCatFile
    executor: ThreadPoolExecutor


class MergeEvaluator:
    """Thread-local Git helpers for independent, parallel merge evaluations."""

    def __init__(self, repository: GitRepository, repo_name: str, slug: str):
        self.repository = repository
        self.repo_name = repo_name
        self.slug = slug
        self.local = threading.local()
        self.resources: list[_EvaluationResources] = []
        self.resources_lock = threading.Lock()

    def _thread_resources(self) -> _EvaluationResources:
        resources = getattr(self.local, "resources", None)
        if resources is not None:
            return resources
        cat_file = BatchCatFile(self.repository)
        cat_file.__enter__()
        try:
            executor = ThreadPoolExecutor(max_workers=6)
        except BaseException:
            cat_file.__exit__(*sys.exc_info())
            raise
        resources = _EvaluationResources(cat_file=cat_file, executor=executor)
        self.local.resources = resources
        with self.resources_lock:
            self.resources.append(resources)
        return resources

    def close(self) -> None:
        """Close helpers after the outer merge-worker pool has stopped."""
        first_error: BaseException | None = None
        for resources in self.resources:
            try:
                resources.executor.shutdown(wait=True, cancel_futures=False)
                resources.cat_file.__exit__(None, None, None)
            except BaseException as error:  # preserve cleanup of later workers
                if first_error is None:
                    first_error = error
        if first_error is not None:
            raise first_error

    def evaluate(
        self,
        merge_oid: str,
        parents: Sequence[str],
    ) -> MergeEvaluation:
        resources = self._thread_resources()
        cat_file = resources.cat_file
        executor = resources.executor
        parent1, parent2 = parents
        merge_future = executor.submit(merge_tree, self.repository, parent1, parent2)
        primary_base = primary_merge_base(self.repository, parent1, parent2)
        if primary_base is None:
            merge_meta = commit_metadata(cat_file, merge_oid)
            parent1_meta = commit_metadata(cat_file, parent1)
            parent2_meta = commit_metadata(cat_file, parent2)
            try:
                merge_outcome = merge_future.result()
            except MergeTreeOperationalError as error:
                merge_tree_status = error.returncode
                merge_tree_sha = hashlib.sha256(error.stdout).hexdigest()
                merge_tree_stderr = decode_git_text(error.stderr)
                merge_tree_stderr_sha = hashlib.sha256(error.stderr).hexdigest()
                merge_tree_result = None
            else:
                merge_tree_status = 1 if merge_outcome[0] else 0
                merge_tree_sha = merge_outcome[4]
                merge_tree_stderr = ""
                merge_tree_stderr_sha = hashlib.sha256(b"").hexdigest()
                merge_tree_result = merge_outcome[1]
            failure_row: dict[str, Any] = {
                "both_sides_touched_tests": None,
                "conflicted": None,
                "conflicted_paths": [],
                "diffs": {"parent1": None, "parent2": None},
                "divergence": None,
                "evaluation_error": {
                    "kind": "no_merge_base",
                    "merge_tree_returncode": merge_tree_status,
                    "merge_tree_stderr": merge_tree_stderr,
                    "merge_tree_stderr_sha256": merge_tree_stderr_sha,
                },
                "evaluation_status": "no_merge_base",
                "merge": merge_oid,
                "merge_base": None,
                "merge_bases": [],
                "merge_message": merge_meta["message"],
                "merge_message_sha256": merge_meta["message_sha256"],
                "merge_tree_output_sha256": merge_tree_sha,
                "miner_protocol_revision": MINER_PROTOCOL_REVISION,
                "miner_source_sha256": MINER_SOURCE_SHA256,
                "multiple_merge_bases": False,
                "parent_subjects": [parent1_meta["subject"], parent2_meta["subject"]],
                "parents": [parent1, parent2],
                "repo": self.repo_name,
                "result_tree": merge_tree_result,
                "schema_version": SCHEMA_VERSION,
            }
            return MergeEvaluation(failure_row, None, False, True)

        all_bases_future = executor.submit(
            self.repository.run, ["merge-base", "--all", parent1, parent2]
        )
        diff1_future = executor.submit(
            repository_diff, self.repository, primary_base, parent1
        )
        diff2_future = executor.submit(
            repository_diff, self.repository, primary_base, parent2
        )
        count1_future = executor.submit(
            commit_count, self.repository, primary_base, parent1
        )
        count2_future = executor.submit(
            commit_count, self.repository, primary_base, parent2
        )
        conflicted, result_tree, stages, messages, merge_tree_sha = merge_future.result()
        all_bases_raw = all_bases_future.result().stdout
        merge_bases = [line.decode("ascii") for line in all_bases_raw.splitlines() if line]
        if primary_base not in merge_bases:
            raise MiningError(
                f"{self.slug}:{merge_oid}: primary merge base missing from --all"
            )
        multiple_bases = len(merge_bases) > 1
        files1, stats1 = diff1_future.result()
        files2, stats2 = diff2_future.result()
        commits1 = count1_future.result()
        commits2 = count2_future.result()

        merge_meta = commit_metadata(cat_file, merge_oid)
        parent1_meta = commit_metadata(cat_file, parent1)
        parent2_meta = commit_metadata(cat_file, parent2)
        base_meta = commit_metadata(cat_file, primary_base)
        delta1 = parent1_meta["committer_epoch"] - base_meta["committer_epoch"]
        delta2 = parent2_meta["committer_epoch"] - base_meta["committer_epoch"]
        negative_clock = delta1 < 0 or delta2 < 0
        lines1 = stats1["lines_changed"]
        lines2 = stats2["lines_changed"]
        combined_lines = None if lines1 is None or lines2 is None else lines1 + lines2

        conflict_message_paths = {
            path
            for message in messages
            if message["type"].startswith("CONFLICT")
            for path in message["paths"]
        }
        stage_paths = {entry["path"] for entry in stages}
        conflict_paths = (
            sorted(conflict_message_paths.union(stage_paths)) if conflicted else []
        )
        common: dict[str, Any] = {
            "both_sides_touched_tests": bool(
                stats1["test_files"] and stats2["test_files"]
            ),
            "conflicted": conflicted,
            "conflicted_paths": conflict_paths,
            "diffs": {"parent1": stats1, "parent2": stats2},
            "divergence": {
                "combined_commits": commits1 + commits2,
                "combined_text_lines_changed": combined_lines,
                "max_wall_clock_seconds": (
                    None if negative_clock else max(delta1, delta2)
                ),
                "negative_clock": negative_clock,
                "parent1": {
                    "commits": commits1,
                    "signed_wall_clock_seconds": delta1,
                    "wall_clock_span_seconds": abs(delta1),
                },
                "parent2": {
                    "commits": commits2,
                    "signed_wall_clock_seconds": delta2,
                    "wall_clock_span_seconds": abs(delta2),
                },
            },
            "evaluation_status": "conflicted" if conflicted else "clean",
            "merge": merge_oid,
            "merge_base": primary_base,
            "merge_bases": sorted(merge_bases),
            "merge_message": merge_meta["message"],
            "merge_message_sha256": merge_meta["message_sha256"],
            "merge_tree_output_sha256": merge_tree_sha,
            "miner_protocol_revision": MINER_PROTOCOL_REVISION,
            "miner_source_sha256": MINER_SOURCE_SHA256,
            "multiple_merge_bases": multiple_bases,
            "parent_subjects": [parent1_meta["subject"], parent2_meta["subject"]],
            "parents": [parent1, parent2],
            "repo": self.repo_name,
            "result_tree": result_tree,
            "schema_version": SCHEMA_VERSION,
        }
        conflict_row: dict[str, Any] | None = None
        if conflicted:
            conflict_row = dict(common)
            conflict_row["conflict_messages"] = [
                message
                for message in messages
                if message["type"].startswith("CONFLICT")
            ]
            conflict_row["conflicts"] = conflict_details(
                self.repository,
                cat_file,
                result_tree,
                conflict_paths,
                stages,
                messages,
            )
            conflict_row["overlap"] = overlap_for_conflicts(
                self.repository, cat_file, conflict_paths, stages
            )
        return MergeEvaluation(common, conflict_row, multiple_bases, False)


def ordered_merge_evaluations(
    evaluator: MergeEvaluator,
    eligible: Sequence[tuple[str, list[str]]],
    *,
    merge_workers: int,
) -> Iterator[tuple[int, MergeEvaluation]]:
    """Evaluate with bounded concurrency and yield in frozen-history order."""
    if merge_workers < 1:
        raise MiningError("merge_workers must be at least 1")
    if not eligible:
        return
    with ThreadPoolExecutor(max_workers=merge_workers) as pool:
        pending: collections.deque[tuple[int, Any]] = collections.deque()
        source = iter(enumerate(eligible, 1))

        def submit_one() -> bool:
            try:
                ordinal, (merge_oid, parents) = next(source)
            except StopIteration:
                return False
            pending.append(
                (ordinal, pool.submit(evaluator.evaluate, merge_oid, parents))
            )
            return True

        for _ in range(merge_workers * 2):
            if not submit_one():
                break
        while pending:
            ordinal, future = pending.popleft()
            yield ordinal, future.result()
            submit_one()


def mine_repository(
    repository_spec: dict[str, Any],
    mirror_root: Path,
    output_root: Path,
    *,
    resume: bool,
    progress_every: int,
    merge_workers: int = 1,
) -> dict[str, Any]:
    slug = repository_spec["slug"]
    repo_name = repository_spec["repo"]
    head = repository_spec.get("frozen_head") or repository_spec.get("head")
    if not head:
        raise MiningError(f"{slug}: manifest lacks frozen_head/head")
    mirror, repository, mirror_verification = validate_task_mirror(
        mirror_root, slug, repository_spec
    )
    resolved_head = repository.text(["rev-parse", f"{head}^{{commit}}"])
    if resolved_head != head:
        raise MiningError(f"{slug}: frozen head resolved to {resolved_head}, expected {head}")
    git_version = repository.text(["version"])
    first_parent_commits, eligible, octopus = list_history(repository, head)

    conflicts_path = output_root / f"{slug}.jsonl"
    all_path = output_root / "_all_merges" / f"{slug}.jsonl"
    summary_path = output_root / "_summaries" / f"{slug}.json"
    all_handle, existing_all = open_partial(all_path, resume)
    conflict_handle, existing_conflicts = open_partial(conflicts_path, resume)
    processed = len(existing_all)
    if processed > len(eligible):
        raise MiningError(f"{slug}: resume data is longer than eligible history")
    for index, row in enumerate(existing_all):
        if row.get("merge") != eligible[index][0] or row.get("repo") != repo_name:
            raise MiningError(f"{slug}: resume prefix does not match frozen history at row {index + 1}")
        if row.get("miner_protocol_revision") != MINER_PROTOCOL_REVISION:
            raise MiningError(
                f"{slug}: resume row {index + 1} uses protocol "
                f"{row.get('miner_protocol_revision')!r}, expected "
                f"{MINER_PROTOCOL_REVISION!r}; restart with --no-resume"
            )
        if row.get("miner_source_sha256") != MINER_SOURCE_SHA256:
            raise MiningError(
                f"{slug}: resume row {index + 1} was produced by a different miner "
                "source; restart with --no-resume"
            )
    expected_conflict_merges = [row["merge"] for row in existing_all if row.get("conflicted")]
    if [row.get("merge") for row in existing_conflicts] != expected_conflict_merges:
        raise MiningError(f"{slug}: conflict resume file is not the all-merges subset")
    if any(
        row.get("miner_protocol_revision") != MINER_PROTOCOL_REVISION
        for row in existing_conflicts
    ):
        raise MiningError(
            f"{slug}: conflict resume file contains a stale protocol revision; "
            "restart with --no-resume"
        )
    if any(
        row.get("miner_source_sha256") != MINER_SOURCE_SHA256
        for row in existing_conflicts
    ):
        raise MiningError(
            f"{slug}: conflict resume file contains a stale miner source hash; "
            "restart with --no-resume"
        )

    clean_count = sum(1 for row in existing_all if row.get("evaluation_status") == "clean")
    conflict_count = len(existing_conflicts)
    conflict_file_occurrences = sum(len(row.get("conflicts", [])) for row in existing_conflicts)
    multiple_base_merges = sum(1 for row in existing_all if row.get("multiple_merge_bases"))
    no_merge_base_merges = sum(
        1 for row in existing_all if row.get("evaluation_status") == "no_merge_base"
    )

    try:
        if merge_workers > 1 and processed < len(eligible):
            evaluator = MergeEvaluator(repository, repo_name, slug)
            try:
                remaining = eligible[processed:]
                for relative_ordinal, evaluation in ordered_merge_evaluations(
                    evaluator,
                    remaining,
                    merge_workers=merge_workers,
                ):
                    ordinal = processed + relative_ordinal
                    # Every worker finishes all parsing and object enrichment before
                    # this ordered checkpoint advances either output file.
                    all_handle.write(canonical_json(evaluation.all_row) + "\n")
                    all_handle.flush()
                    if evaluation.no_merge_base:
                        no_merge_base_merges += 1
                    elif evaluation.conflict_row is not None:
                        conflict_handle.write(
                            canonical_json(evaluation.conflict_row) + "\n"
                        )
                        conflict_handle.flush()
                        conflict_count += 1
                        conflict_file_occurrences += len(
                            evaluation.conflict_row["conflicts"]
                        )
                    else:
                        clean_count += 1
                    if evaluation.multiple_merge_bases:
                        multiple_base_merges += 1
                    if progress_every and ordinal % progress_every == 0:
                        print(
                            f"{slug}: {ordinal}/{len(eligible)} eligible merges, "
                            f"{conflict_count} conflicted",
                            file=sys.stderr,
                            flush=True,
                        )
            finally:
                evaluator.close()
            processed = len(eligible)
        with BatchCatFile(repository) as cat_file, ThreadPoolExecutor(max_workers=6) as executor:
            for ordinal, (merge_oid, parents) in enumerate(eligible[processed:], processed + 1):
                parent1, parent2 = parents
                merge_future = executor.submit(merge_tree, repository, parent1, parent2)
                primary_base = primary_merge_base(repository, parent1, parent2)
                if primary_base is None:
                    merge_meta = commit_metadata(cat_file, merge_oid)
                    parent1_meta = commit_metadata(cat_file, parent1)
                    parent2_meta = commit_metadata(cat_file, parent2)
                    try:
                        merge_outcome = merge_future.result()
                    except MergeTreeOperationalError as error:
                        merge_tree_status = error.returncode
                        merge_tree_sha = hashlib.sha256(error.stdout).hexdigest()
                        merge_tree_stderr = decode_git_text(error.stderr)
                        merge_tree_stderr_sha = hashlib.sha256(error.stderr).hexdigest()
                        merge_tree_result = None
                    else:
                        merge_tree_status = 1 if merge_outcome[0] else 0
                        merge_tree_sha = merge_outcome[4]
                        merge_tree_stderr = ""
                        merge_tree_stderr_sha = hashlib.sha256(b"").hexdigest()
                        merge_tree_result = merge_outcome[1]
                    failure_row: dict[str, Any] = {
                        "both_sides_touched_tests": None,
                        "conflicted": None,
                        "conflicted_paths": [],
                        "diffs": {"parent1": None, "parent2": None},
                        "divergence": None,
                        "evaluation_error": {
                            "kind": "no_merge_base",
                            "merge_tree_returncode": merge_tree_status,
                            "merge_tree_stderr": merge_tree_stderr,
                            "merge_tree_stderr_sha256": merge_tree_stderr_sha,
                        },
                        "evaluation_status": "no_merge_base",
                        "merge": merge_oid,
                        "merge_base": None,
                        "merge_bases": [],
                        "merge_message": merge_meta["message"],
                        "merge_message_sha256": merge_meta["message_sha256"],
                        "merge_tree_output_sha256": merge_tree_sha,
                        "miner_protocol_revision": MINER_PROTOCOL_REVISION,
                        "miner_source_sha256": MINER_SOURCE_SHA256,
                        "multiple_merge_bases": False,
                        "parent_subjects": [
                            parent1_meta["subject"],
                            parent2_meta["subject"],
                        ],
                        "parents": [parent1, parent2],
                        "repo": repo_name,
                        "result_tree": merge_tree_result,
                        "schema_version": SCHEMA_VERSION,
                    }
                    all_handle.write(canonical_json(failure_row) + "\n")
                    all_handle.flush()
                    no_merge_base_merges += 1
                    if progress_every and ordinal % progress_every == 0:
                        print(
                            f"{slug}: {ordinal}/{len(eligible)} eligible merges, "
                            f"{conflict_count} conflicted",
                            file=sys.stderr,
                            flush=True,
                        )
                    continue
                all_bases_future = executor.submit(
                    repository.run, ["merge-base", "--all", parent1, parent2]
                )
                diff1_future = executor.submit(repository_diff, repository, primary_base, parent1)
                diff2_future = executor.submit(repository_diff, repository, primary_base, parent2)
                count1_future = executor.submit(commit_count, repository, primary_base, parent1)
                count2_future = executor.submit(commit_count, repository, primary_base, parent2)
                conflicted, result_tree, stages, messages, merge_tree_sha = merge_future.result()
                all_bases_raw = all_bases_future.result().stdout
                merge_bases = [line.decode("ascii") for line in all_bases_raw.splitlines() if line]
                if primary_base not in merge_bases:
                    raise MiningError(f"{slug}:{merge_oid}: primary merge base missing from --all")
                multiple_bases = len(merge_bases) > 1
                if multiple_bases:
                    multiple_base_merges += 1
                files1, stats1 = diff1_future.result()
                files2, stats2 = diff2_future.result()
                commits1 = count1_future.result()
                commits2 = count2_future.result()

                merge_meta = commit_metadata(cat_file, merge_oid)
                parent1_meta = commit_metadata(cat_file, parent1)
                parent2_meta = commit_metadata(cat_file, parent2)
                base_meta = commit_metadata(cat_file, primary_base)
                delta1 = parent1_meta["committer_epoch"] - base_meta["committer_epoch"]
                delta2 = parent2_meta["committer_epoch"] - base_meta["committer_epoch"]
                negative_clock = delta1 < 0 or delta2 < 0
                lines1 = stats1["lines_changed"]
                lines2 = stats2["lines_changed"]
                combined_lines = None if lines1 is None or lines2 is None else lines1 + lines2

                conflict_message_paths = {
                    path
                    for message in messages
                    if message["type"].startswith("CONFLICT")
                    for path in message["paths"]
                }
                stage_paths = {entry["path"] for entry in stages}
                conflict_paths = sorted(conflict_message_paths.union(stage_paths)) if conflicted else []

                common: dict[str, Any] = {
                    "both_sides_touched_tests": bool(stats1["test_files"] and stats2["test_files"]),
                    "conflicted": conflicted,
                    "conflicted_paths": conflict_paths,
                    "diffs": {"parent1": stats1, "parent2": stats2},
                    "divergence": {
                        "combined_commits": commits1 + commits2,
                        "combined_text_lines_changed": combined_lines,
                        "max_wall_clock_seconds": None if negative_clock else max(delta1, delta2),
                        "negative_clock": negative_clock,
                        "parent1": {
                            "commits": commits1,
                            "signed_wall_clock_seconds": delta1,
                            "wall_clock_span_seconds": abs(delta1),
                        },
                        "parent2": {
                            "commits": commits2,
                            "signed_wall_clock_seconds": delta2,
                            "wall_clock_span_seconds": abs(delta2),
                        },
                    },
                    "evaluation_status": "conflicted" if conflicted else "clean",
                    "merge": merge_oid,
                    "merge_base": primary_base,
                    "merge_bases": sorted(merge_bases),
                    "merge_message": merge_meta["message"],
                    "merge_message_sha256": merge_meta["message_sha256"],
                    "merge_tree_output_sha256": merge_tree_sha,
                    "miner_protocol_revision": MINER_PROTOCOL_REVISION,
                    "miner_source_sha256": MINER_SOURCE_SHA256,
                    "multiple_merge_bases": multiple_bases,
                    "parent_subjects": [parent1_meta["subject"], parent2_meta["subject"]],
                    "parents": [parent1, parent2],
                    "repo": repo_name,
                    "result_tree": result_tree,
                    "schema_version": SCHEMA_VERSION,
                }
                conflict_row: dict[str, Any] | None = None
                if conflicted:
                    conflict_row = dict(common)
                    conflict_row["conflict_messages"] = [
                        message for message in messages if message["type"].startswith("CONFLICT")
                    ]
                    conflict_row["conflicts"] = conflict_details(
                        repository,
                        cat_file,
                        result_tree,
                        conflict_paths,
                        stages,
                        messages,
                    )
                    conflict_row["overlap"] = overlap_for_conflicts(
                        repository, cat_file, conflict_paths, stages
                    )

                # Finish every fallible enrichment step before advancing either
                # checkpoint.  A parser/object failure can then be fixed and
                # resumed without leaving a conflicted all-merges row whose
                # conflict-only counterpart was never written.
                all_handle.write(canonical_json(common) + "\n")
                all_handle.flush()
                if conflict_row is not None:
                    conflict_handle.write(canonical_json(conflict_row) + "\n")
                    conflict_handle.flush()
                    conflict_count += 1
                    conflict_file_occurrences += len(conflict_row["conflicts"])
                else:
                    clean_count += 1

                if progress_every and ordinal % progress_every == 0:
                    print(
                        f"{slug}: {ordinal}/{len(eligible)} eligible merges, "
                        f"{conflict_count} conflicted",
                        file=sys.stderr,
                        flush=True,
                    )
    finally:
        all_handle.close()
        conflict_handle.close()

    all_partial = all_path.with_name(all_path.name + ".partial")
    conflict_partial = conflicts_path.with_name(conflicts_path.name + ".partial")
    os.replace(all_partial, all_path)
    os.replace(conflict_partial, conflicts_path)
    summary = {
        "classification_revision": CLASSIFICATION_REVISION,
        "classification_rule": CLASSIFICATION_RULE,
        "clean_merges": clean_count,
        "conflict_file_occurrences": conflict_file_occurrences,
        "conflict_range_revision": CONFLICT_RANGE_REVISION,
        "conflicted_merges": conflict_count,
        "eligible_two_parent_merges": len(eligible),
        "evaluable_merges": clean_count + conflict_count,
        "excluded_octopus_merges": octopus,
        "failed_merges": len(eligible) - clean_count - conflict_count,
        "first_parent_commits": first_parent_commits,
        "first_parent_merges": len(eligible) + octopus,
        "git_version": git_version,
        "git_environment_overrides": dict(
            sorted(DETERMINISTIC_GIT_ENVIRONMENT_OVERRIDES.items())
        ),
        "git_environment_scrubbed": {
            "exact": list(SCRUBBED_GIT_ENVIRONMENT_KEYS),
            "prefixes": list(SCRUBBED_GIT_ENVIRONMENT_PREFIXES),
        },
        "head": head,
        "merge_tree_interpretation": MERGE_TREE_INTERPRETATION,
        "merge_tree_invocation": list(MERGE_TREE_INVOCATION),
        "miner_protocol_revision": MINER_PROTOCOL_REVISION,
        "miner_source_sha256": MINER_SOURCE_SHA256,
        "mirror_verification": mirror_verification,
        "multiple_merge_base_merges": multiple_base_merges,
        "no_merge_base_merges": no_merge_base_merges,
        "output_sha256": {
            "all_merges": sha256_file(all_path),
            "conflicts": sha256_file(conflicts_path),
        },
        "overlap_revision": OVERLAP_REVISION,
        "overlap_rule": OVERLAP_RULE,
        "repo": repo_name,
        "python_implementation": platform.python_implementation(),
        "python_version": platform.python_version(),
        "schema_version": SCHEMA_VERSION,
        "slug": slug,
        "storage_policy": STORAGE_POLICY,
        "test_path_revision": TEST_PATH_REVISION,
        "test_path_rule": TEST_PATH_RULE,
    }
    atomic_json(summary_path, summary)
    print(
        f"{slug}: complete; {conflict_count}/{len(eligible)} eligible merges conflicted",
        file=sys.stderr,
        flush=True,
    )
    return summary


def load_manifest(path: Path) -> list[dict[str, Any]]:
    value = json.loads(path.read_text(encoding="utf-8"))
    repositories = value.get("repositories") if isinstance(value, dict) else value
    if not isinstance(repositories, list):
        raise MiningError("repository manifest must contain a repositories list")
    return repositories


def parse_args(arguments: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--mirror-root", type=Path, default=DEFAULT_MIRROR_ROOT)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--repo", action="append", dest="repos", help="slug to mine; repeatable")
    parser.add_argument("--resume", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--progress-every", type=int, default=100)
    parser.add_argument(
        "--merge-workers",
        type=int,
        default=1,
        help=(
            "independent merge evaluations per repository; rows are still written "
            "strictly in first-parent order"
        ),
    )
    return parser.parse_args(arguments)


def main(arguments: Sequence[str] | None = None) -> int:
    args = parse_args(arguments)
    if args.merge_workers < 1:
        raise MiningError("--merge-workers must be at least 1")
    repositories = load_manifest(args.manifest)
    if args.repos:
        requested = set(args.repos)
        available = {repo["slug"] for repo in repositories}
        unknown = sorted(requested - available)
        if unknown:
            raise MiningError(f"unknown repository slug(s): {', '.join(unknown)}")
        repositories = [repo for repo in repositories if repo["slug"] in requested]
    summaries = []
    for repository_spec in repositories:
        with RepositoryLock(args.output_root, repository_spec["slug"]):
            summaries.append(
                mine_repository(
                    repository_spec,
                    args.mirror_root,
                    args.output_root,
                    resume=args.resume,
                    progress_every=args.progress_every,
                    merge_workers=args.merge_workers,
                )
            )
    print(canonical_json({"repositories": summaries, "schema_version": SCHEMA_VERSION}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
