/*
 * Byte-restoring Java source perturbation for the arms-ladder instrument.
 *
 * JavaParser identifies method declarations and LexicalPreservingPrinter
 * renders the temporary perturbation.  The original bytes are kept outside
 * the target file and are the only bytes ever used for restoration.
 */

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.stmt.Statement;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Properties;

public final class JavaPerturber {
    private static final String SCHEMA_VERSION = "1";
    private static final String ORIGINAL_NAME = "original.bin";
    private static final String MANIFEST_NAME = "manifest.properties";
    private static final byte[] UTF8_BOM = new byte[] {(byte) 0xef, (byte) 0xbb, (byte) 0xbf};
    private static final String PERTURBATION =
            "if (true) throw new RuntimeException(\"perturbed\");";
    private static final List<String> GENERATED_SEGMENTS = Collections.unmodifiableList(
            Arrays.asList("target", "build", "gen", "generated", "generated-sources", "autogenerated"));

    private JavaPerturber() {
    }

    public static void main(String[] arguments) {
        try {
            Arguments parsed = Arguments.parse(arguments);
            if ("apply".equals(parsed.command)) {
                apply(parsed.file, parsed.state);
            } else if ("restore".equals(parsed.command)) {
                restore(parsed.file, parsed.state);
            } else if ("plan".equals(parsed.command)) {
                plan(parsed.file);
            } else if ("classify".equals(parsed.command)) {
                classify(parsed.file);
            } else {
                throw new UsageException("unknown command: " + parsed.command);
            }
        } catch (UsageException exception) {
            System.err.println(exception.getMessage());
            System.err.println(
                    "usage: JavaPerturber (apply|restore) --file <source.java> --state <directory>\n"
                    + "       JavaPerturber (plan|classify) --file <source.java>");
            System.exit(2);
        } catch (Exception exception) {
            System.err.println(exception.getClass().getSimpleName() + ": " + exception.getMessage());
            System.exit(1);
        }
    }

    private static void apply(Path requestedFile, Path requestedState) throws Exception {
        Path file = requireJavaFile(requestedFile);
        Path state = requestedState.toAbsolutePath().normalize();
        if (Files.exists(state)) {
            throw new IOException("state directory already exists: " + state);
        }

        byte[] original = Files.readAllBytes(file);
        GeneratedClassification classification = classifyGenerated(file, original);
        if (classification.generated) {
            throw new IOException("generated source is excluded (" + classification.reason + "): " + file);
        }

        Files.createDirectories(state);
        Path originalPath = state.resolve(ORIGINAL_NAME);
        atomicWrite(originalPath, original);

        boolean bom = startsWith(original, UTF8_BOM);
        JavaParser parser = parser();
        CompilationUnit unit = parseCompilationUnit(parser, original);
        LexicalPreservingPrinter.setup(unit);
        List<MethodDeclaration> methods = new ArrayList<MethodDeclaration>(
                unit.findAll(MethodDeclaration.class));
        int injected = 0;
        for (MethodDeclaration method : methods) {
            if (!method.getBody().isPresent()) {
                continue;
            }
            ParseResult<Statement> statementResult = parser.parseStatement(PERTURBATION);
            if (!statementResult.isSuccessful() || !statementResult.getResult().isPresent()) {
                throw new IOException("JavaParser rejected the fixed perturbation statement");
            }
            method.getBody().get().addStatement(0, statementResult.getResult().get());
            injected += 1;
        }
        if (injected == 0) {
            throw new IOException("target has no concrete method body: " + file);
        }

        byte[] rendered = LexicalPreservingPrinter.print(unit).getBytes(StandardCharsets.UTF_8);
        byte[] perturbed = bom ? concatenate(UTF8_BOM, rendered) : rendered;
        String originalHash = sha256(original);
        String perturbedHash = sha256(perturbed);
        if (originalHash.equals(perturbedHash)) {
            throw new IOException("perturbation did not change the target bytes");
        }

        Properties manifest = new Properties();
        manifest.setProperty("schemaVersion", SCHEMA_VERSION);
        manifest.setProperty("status", "prepared");
        manifest.setProperty("file", file.toString());
        manifest.setProperty("originalSha256", originalHash);
        manifest.setProperty("perturbedSha256", perturbedHash);
        manifest.setProperty("injectedMethodBodies", Integer.toString(injected));
        manifest.setProperty("javaParserVersion", javaParserVersion());
        manifest.setProperty("preparedAtUtc", Instant.now().toString());
        writeManifest(state, manifest);

        String observedPerturbedHash;
        try {
            atomicWrite(file, perturbed);
            observedPerturbedHash = sha256(Files.readAllBytes(file));
            if (!perturbedHash.equals(observedPerturbedHash)) {
                throw new IOException("post-write perturbed hash mismatch for " + file);
            }
            manifest.setProperty("status", "applied");
            manifest.setProperty("appliedAtUtc", Instant.now().toString());
            manifest.setProperty("observedPerturbedSha256", observedPerturbedHash);
            writeManifest(state, manifest);
        } catch (Exception exception) {
            try {
                rollbackAfterApplyFailure(file, original, originalHash, perturbedHash);
            } catch (Exception rollbackException) {
                exception.addSuppressed(rollbackException);
            }
            throw exception;
        }

        printJson(
                "apply",
                file,
                state,
                originalHash,
                perturbedHash,
                injected,
                "applied");
    }

    private static void restore(Path requestedFile, Path requestedState) throws Exception {
        Path file = requireJavaFile(requestedFile);
        Path state = requestedState.toAbsolutePath().normalize();
        Properties manifest = readManifest(state);
        if (!SCHEMA_VERSION.equals(manifest.getProperty("schemaVersion"))) {
            throw new IOException("unsupported state schema in " + state);
        }
        if (!file.toString().equals(manifest.getProperty("file"))) {
            throw new IOException("state belongs to a different target: " + manifest.getProperty("file"));
        }

        Path originalPath = state.resolve(ORIGINAL_NAME);
        byte[] original = Files.readAllBytes(originalPath);
        String expectedOriginal = requireProperty(manifest, "originalSha256");
        String expectedPerturbed = requireProperty(manifest, "perturbedSha256");
        String backupHash = sha256(original);
        if (!expectedOriginal.equals(backupHash)) {
            throw new IOException("saved original hash mismatch in " + state);
        }

        String currentHash = sha256(Files.readAllBytes(file));
        if (expectedOriginal.equals(currentHash)) {
            manifest.setProperty("status", "restored");
            manifest.setProperty("restoredAtUtc", Instant.now().toString());
            manifest.setProperty("observedRestoredSha256", currentHash);
            writeManifest(state, manifest);
            printJson(
                    "restore",
                    file,
                    state,
                    expectedOriginal,
                    expectedPerturbed,
                    Integer.parseInt(requireProperty(manifest, "injectedMethodBodies")),
                    "already-restored-hash-verified");
            return;
        }
        if (!expectedPerturbed.equals(currentHash)) {
            throw new IOException(
                    "refusing to overwrite target changed after perturbation; expected "
                    + expectedPerturbed + " but observed " + currentHash);
        }

        atomicWrite(file, original);
        String restoredHash = sha256(Files.readAllBytes(file));
        if (!expectedOriginal.equals(restoredHash)) {
            throw new IOException("restored bytes do not match the recorded original hash");
        }
        manifest.setProperty("status", "restored");
        manifest.setProperty("restoredAtUtc", Instant.now().toString());
        manifest.setProperty("observedRestoredSha256", restoredHash);
        writeManifest(state, manifest);
        printJson(
                "restore",
                file,
                state,
                expectedOriginal,
                expectedPerturbed,
                Integer.parseInt(requireProperty(manifest, "injectedMethodBodies")),
                "restored-hash-verified");
    }

    private static void classify(Path requestedFile) throws Exception {
        Path file = requireJavaFile(requestedFile);
        GeneratedClassification classification = classifyGenerated(file, Files.readAllBytes(file));
        System.out.println(
                "{\"event\":\"classify\",\"file\":\"" + jsonEscape(file.toString())
                + "\",\"generated\":" + classification.generated
                + ",\"reason\":\"" + jsonEscape(classification.reason) + "\"}");
    }

    private static void plan(Path requestedFile) throws Exception {
        Path file = requireJavaFile(requestedFile);
        byte[] original = Files.readAllBytes(file);
        GeneratedClassification classification = classifyGenerated(file, original);
        if (classification.generated) {
            System.out.println(
                    "{\"event\":\"plan\",\"file\":\"" + jsonEscape(file.toString())
                    + "\",\"eligible\":false,\"generated\":true,\"reason\":\""
                    + jsonEscape(classification.reason) + "\",\"concreteMethodBodies\":0}");
            return;
        }
        CompilationUnit unit = parseCompilationUnit(parser(), original);
        int bodies = 0;
        for (MethodDeclaration method : unit.findAll(MethodDeclaration.class)) {
            if (method.getBody().isPresent()) {
                bodies += 1;
            }
        }
        System.out.println(
                "{\"event\":\"plan\",\"file\":\"" + jsonEscape(file.toString())
                + "\",\"eligible\":" + (bodies > 0)
                + ",\"generated\":false,\"reason\":\""
                + jsonEscape(bodies > 0 ? "concrete method body present" : "no concrete method body")
                + "\",\"concreteMethodBodies\":" + bodies + "}");
    }

    private static JavaParser parser() {
        ParserConfiguration configuration = new ParserConfiguration();
        configuration.setLanguageLevel(ParserConfiguration.LanguageLevel.BLEEDING_EDGE);
        return new JavaParser(configuration);
    }

    private static CompilationUnit parseCompilationUnit(JavaParser parser, byte[] original)
            throws IOException {
        boolean bom = startsWith(original, UTF8_BOM);
        byte[] sourceBytes = bom
                ? Arrays.copyOfRange(original, UTF8_BOM.length, original.length)
                : original;
        String source = decodeUtf8(sourceBytes);
        ParseResult<CompilationUnit> result = parser.parse(source);
        if (!result.isSuccessful() || !result.getResult().isPresent()) {
            throw new IOException("JavaParser rejected source: " + result.getProblems());
        }
        return result.getResult().get();
    }

    private static void rollbackAfterApplyFailure(
            Path file,
            byte[] original,
            String originalHash,
            String perturbedHash) throws IOException {
        String currentHash = sha256(Files.readAllBytes(file));
        if (originalHash.equals(currentHash)) {
            return;
        }
        if (!perturbedHash.equals(currentHash)) {
            throw new IOException(
                    "cannot roll back apply failure: target has unexpected hash " + currentHash);
        }
        atomicWrite(file, original);
        String restoredHash = sha256(Files.readAllBytes(file));
        if (!originalHash.equals(restoredHash)) {
            throw new IOException("apply-failure rollback did not restore the original hash");
        }
    }

    private static Path requireJavaFile(Path requested) throws IOException {
        Path file = requested.toAbsolutePath().normalize();
        if (!file.getFileName().toString().endsWith(".java")) {
            throw new IOException("target is not a .java file: " + file);
        }
        if (!Files.isRegularFile(file)) {
            throw new IOException("target is not a regular file: " + file);
        }
        return file;
    }

    private static GeneratedClassification classifyGenerated(Path file, byte[] bytes) {
        String name = file.getFileName().toString().toLowerCase(Locale.ROOT);
        if (name.endsWith(".generated.java")) {
            return new GeneratedClassification(true, "generated filename suffix");
        }
        for (Path segment : file) {
            String lower = segment.toString().toLowerCase(Locale.ROOT);
            if (GENERATED_SEGMENTS.contains(lower)) {
                return new GeneratedClassification(true, "generated path segment " + lower);
            }
        }
        int headerLength = Math.min(bytes.length, 8192);
        String header = new String(bytes, 0, headerLength, StandardCharsets.UTF_8)
                .toLowerCase(Locale.ROOT);
        if (header.contains("@generated")) {
            return new GeneratedClassification(true, "@generated header marker");
        }
        if (header.contains("automatically generated")) {
            return new GeneratedClassification(true, "automatically-generated header marker");
        }
        if (header.contains("generated") && header.contains("do not edit")) {
            return new GeneratedClassification(true, "generated/do-not-edit header marker");
        }
        return new GeneratedClassification(false, "no generated-source rule matched");
    }

    private static String decodeUtf8(byte[] bytes) throws CharacterCodingException {
        CharBuffer decoded = StandardCharsets.UTF_8.newDecoder()
                .onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT)
                .decode(ByteBuffer.wrap(bytes));
        return decoded.toString();
    }

    private static void atomicWrite(Path destination, byte[] bytes) throws IOException {
        Path parent = destination.toAbsolutePath().getParent();
        if (parent == null) {
            throw new IOException("destination has no parent: " + destination);
        }
        Files.createDirectories(parent);
        Path temporary = Files.createTempFile(parent, destination.getFileName().toString(), ".tmp");
        try {
            Files.write(temporary, bytes);
            try {
                Files.move(
                        temporary,
                        destination,
                        StandardCopyOption.ATOMIC_MOVE,
                        StandardCopyOption.REPLACE_EXISTING);
            } catch (AtomicMoveNotSupportedException exception) {
                Files.move(temporary, destination, StandardCopyOption.REPLACE_EXISTING);
            }
        } finally {
            Files.deleteIfExists(temporary);
        }
    }

    private static void writeManifest(Path state, Properties manifest) throws IOException {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        try (OutputStream output = buffer) {
            manifest.store(output, "Java arms perturbation state; original.bin is authoritative");
        }
        atomicWrite(state.resolve(MANIFEST_NAME), buffer.toByteArray());
    }

    private static Properties readManifest(Path state) throws IOException {
        Path path = state.resolve(MANIFEST_NAME);
        Properties properties = new Properties();
        byte[] bytes = Files.readAllBytes(path);
        try (InputStream input = new ByteArrayInputStream(bytes)) {
            properties.load(input);
        }
        return properties;
    }

    private static String requireProperty(Properties properties, String key) throws IOException {
        String value = properties.getProperty(key);
        if (value == null || value.isEmpty()) {
            throw new IOException("missing state property: " + key);
        }
        return value;
    }

    private static String sha256(byte[] bytes) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] value = digest.digest(bytes);
            StringBuilder result = new StringBuilder(value.length * 2);
            for (byte item : value) {
                result.append(String.format(Locale.ROOT, "%02x", item & 0xff));
            }
            return result.toString();
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 is unavailable", exception);
        }
    }

    private static boolean startsWith(byte[] value, byte[] prefix) {
        if (value.length < prefix.length) {
            return false;
        }
        for (int index = 0; index < prefix.length; index += 1) {
            if (value[index] != prefix[index]) {
                return false;
            }
        }
        return true;
    }

    private static byte[] concatenate(byte[] first, byte[] second) {
        byte[] result = Arrays.copyOf(first, first.length + second.length);
        System.arraycopy(second, 0, result, first.length, second.length);
        return result;
    }

    private static String javaParserVersion() {
        Package parserPackage = JavaParser.class.getPackage();
        String version = parserPackage == null ? null : parserPackage.getImplementationVersion();
        return version == null ? "unknown" : version;
    }

    private static void printJson(
            String event,
            Path file,
            Path state,
            String originalHash,
            String perturbedHash,
            int injected,
            String status) {
        System.out.println(
                "{\"event\":\"" + jsonEscape(event)
                + "\",\"file\":\"" + jsonEscape(file.toString())
                + "\",\"state\":\"" + jsonEscape(state.toString())
                + "\",\"originalSha256\":\"" + originalHash
                + "\",\"perturbedSha256\":\"" + perturbedHash
                + "\",\"injectedMethodBodies\":" + injected
                + ",\"status\":\"" + jsonEscape(status) + "\"}");
    }

    private static String jsonEscape(String value) {
        StringBuilder result = new StringBuilder(value.length() + 16);
        for (int index = 0; index < value.length(); index += 1) {
            char item = value.charAt(index);
            switch (item) {
                case '\\':
                    result.append("\\\\");
                    break;
                case '"':
                    result.append("\\\"");
                    break;
                case '\b':
                    result.append("\\b");
                    break;
                case '\f':
                    result.append("\\f");
                    break;
                case '\n':
                    result.append("\\n");
                    break;
                case '\r':
                    result.append("\\r");
                    break;
                case '\t':
                    result.append("\\t");
                    break;
                default:
                    if (item < 0x20) {
                        result.append(String.format(Locale.ROOT, "\\u%04x", (int) item));
                    } else {
                        result.append(item);
                    }
            }
        }
        return result.toString();
    }

    private static final class GeneratedClassification {
        private final boolean generated;
        private final String reason;

        private GeneratedClassification(boolean generated, String reason) {
            this.generated = generated;
            this.reason = reason;
        }
    }

    private static final class Arguments {
        private final String command;
        private final Path file;
        private final Path state;

        private Arguments(String command, Path file, Path state) {
            this.command = command;
            this.file = file;
            this.state = state;
        }

        private static Arguments parse(String[] arguments) throws UsageException {
            if (arguments.length < 3) {
                throw new UsageException("missing arguments");
            }
            String command = arguments[0];
            Path file = null;
            Path state = null;
            for (int index = 1; index < arguments.length; index += 1) {
                String item = arguments[index];
                if ("--file".equals(item) && index + 1 < arguments.length) {
                    file = Paths.get(arguments[++index]);
                } else if ("--state".equals(item) && index + 1 < arguments.length) {
                    state = Paths.get(arguments[++index]);
                } else {
                    throw new UsageException("unknown or incomplete argument: " + item);
                }
            }
            if (file == null) {
                throw new UsageException("--file is required");
            }
            if (!("apply".equals(command) || "restore".equals(command)
                    || "plan".equals(command) || "classify".equals(command))) {
                throw new UsageException("command must be apply, restore, plan, or classify");
            }
            if (!("classify".equals(command) || "plan".equals(command)) && state == null) {
                throw new UsageException("--state is required for " + command);
            }
            return new Arguments(command, file, state);
        }
    }

    private static final class UsageException extends Exception {
        private UsageException(String message) {
            super(message);
        }
    }
}
